# Generated by Django 3.1.3 on 2020-11-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='url',
            new_name='urlPic',
        ),
    ]
